server:
  port: 8900

spring:
  application:
    name: consumer-8900-feign
  zipkin:
    base-url: http://localhost:9411
eureka:
  client:
    service-url:
      defaultZone: http://dcy8700.com:8700/eureka/
feign:
  hystrix:
    enabled: true